// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
	DATABASE_URL: string;
	AI_API_KEY: string;
}
