// import '../styles/globals.css'
// import '../styles/index.scss'

export { default as AccordionInfo } from './AccordionInfo/AccordionInfo'
export { default as Alert } from './Alert/Alert'
export { default as Button } from './Button/Button'
export { default as Checkbox } from './Checkbox/Checkbox'
export { default as DropDown } from './DropDown/NcDropDown'
export { default as Drawer } from './Drawer/Drawer'
export { default as Input } from './Input/Input'
export { default as Modal } from './Modal/NcModal'
export { default as Radio } from './Radio/Radio'
export { default as Select } from './Select/Select'
export { default as Textarea } from './TextArea/Textarea'
export { default as Avatar } from './Avatar/Avatar'
export { default as Heading } from './Heading/Heading'
export { default as Image } from './Image/NcImage'
export { default as MySwitch } from './MySwitch/MySwitch'
export { default as Label } from './Label/Label'
export { default as ButtonPrimary } from './Button/ButtonPrimary'
export { default as ButtonSecondary } from './Button/ButtonSecondary'
export { default as ButtonCircle } from './Button/ButtonCircle'
export { default as ButtonThird } from './Button/ButtonThird'
export { default as Loading } from './Button/Loading'
export { default as ButtonClose } from './ButtonClose/ButtonClose'
export { default as Img } from './Image/NcImage'
export { default as Heading2 } from './Heading/Heading2'
export { default as MyLink } from './MyLink/MyLink'
export { default as PlaceIcon } from './Image/PlaceIcon'
export { default as Nav } from './Nav/Nav'
export { default as NavItem } from './NavItem/NavItem'
export { default as DateTimePicker } from './DateTimePicker/DateTimePicker'
export type { DropDownItem } from './DropDown/NcDropDown'
export type { ButtonProps } from './Button/Button'
