import './globals.css'
import '@/styles/index.scss'
import { Poppins } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'

import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

import AuthProvider from '@/providers/AuthProvider'

// do not cache this layout
export const revalidate = 0

export const metadata = {
    title: 'Athera',
    description: 'Generated by create next app',
}

const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    weight: ['300', '400', '500', '600', '700'],
})

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const supabase = createServerComponentClient({ cookies })

    const {
        data: { session },
    } = await supabase.auth.getSession()

    const accessToken = session?.access_token || ''
    return (
        <html lang="en" className={poppins.className}>
            <body className="bg-[#f8f8f8] text-base dark:bg-neutral-900/95 text-neutral-900 dark:text-neutral-200">
                <Header />
                <AuthProvider accessToken={accessToken}>
                    {children}
                </AuthProvider>
                <Footer />
            </body>
        </html>
    )
}
