export async function getUserCountry(): Promise<string | null> {
    try {
        const tz = Intl.DateTimeFormat().resolvedOptions().timeZone
        console.log(`Timezone: ${tz}`)
        // Simple mapping of timezones to countries (expand as needed)
        const timezoneCountryMap: Record<string, string> = {
            'America/New_York': 'us',
            'America/Los_Angeles': 'us',
            'America/Chicago': 'us',
            'America/Denver': 'us',
            'America/Phoenix': 'us',
            'America/Toronto': 'ca',
            'America/Vancouver': 'ca',
            'America/Mexico_City': 'mx',
            'America/Argentina/Buenos_Aires': 'ar',
            'America/Bogota': 'co',
            'America/Lima': 'pe',
            'America/Santiago': 'cl',
            'America/Caracas': 've',
            'America/Guatemala': 'gt',
            'America/Montevideo': 'uy',
            'America/La_Paz': 'bo',
            'America/Panama': 'pa',
            'America/Havana': 'cu',
            'America/El_Salvador': 'sv',
            'America/Santo_Domingo': 'do',
            'Europe/London': 'gb',
            'Europe/Paris': 'fr',
            'Europe/Berlin': 'de',
            'Europe/Madrid': 'es',
            'Europe/Rome': 'it',
            'Europe/Amsterdam': 'nl',
            'Europe/Brussels': 'be',
            'Europe/Zurich': 'ch',
            'Europe/Stockholm': 'se',
            'Europe/Oslo': 'no',
            'Europe/Copenhagen': 'dk',
            'Europe/Warsaw': 'pl',
            'Europe/Athens': 'gr',
            'Europe/Helsinki': 'fi',
            'Europe/Budapest': 'hu',
            'Europe/Prague': 'cz',
            'Europe/Vienna': 'at',
            'Europe/Dublin': 'ie',
            'Europe/Lisbon': 'pt',
            'Europe/Sofia': 'bg',
            'Europe/Bucharest': 'ro',
            'Europe/Istanbul': 'tr',
            'Asia/Tokyo': 'jp',
            'Asia/Seoul': 'kr',
            'Asia/Shanghai': 'cn',
            'Asia/Hong_Kong': 'hk',
            'Asia/Singapore': 'sg',
            'Asia/Kuala_Lumpur': 'my',
            'Asia/Bangkok': 'th',
            'Asia/Jakarta': 'id',
            'Asia/Manila': 'ph',
            'Asia/Calcutta': 'in',
            'Asia/Dubai': 'ae',
            'Asia/Riyadh': 'sa',
            'Asia/Tehran': 'ir',
            'Asia/Baghdad': 'iq',
            'Asia/Karachi': 'pk',
            'Asia/Kathmandu': 'np',
            'Asia/Dhaka': 'bd',
            'Asia/Taipei': 'tw',
            'Asia/Ho_Chi_Minh': 'vn',
            'Asia/Jerusalem': 'il',
            'Asia/Amman': 'jo',
            'Asia/Beirut': 'lb',
            'Asia/Colombo': 'lk',
            'Asia/Yangon': 'mm',
            'Asia/Tashkent': 'uz',
            'Asia/Almaty': 'kz',
            'Australia/Sydney': 'au',
            'Australia/Melbourne': 'au',
            'Australia/Perth': 'au',
            'Pacific/Auckland': 'nz',
            'Pacific/Fiji': 'fj',
            'Pacific/Port_Moresby': 'pg',
            'Africa/Lagos': 'ng',
            'Africa/Johannesburg': 'za',
            'Africa/Cairo': 'eg',
            'Africa/Nairobi': 'ke',
            'Africa/Accra': 'gh',
            'Africa/Algiers': 'dz',
            'Africa/Casablanca': 'ma',
            'Africa/Addis_Ababa': 'et',
            'Africa/Dakar': 'sn',
            'Africa/Abidjan': 'ci',
            'Africa/Tunis': 'tn',
            'Africa/Kampala': 'ug',
            'Africa/Harare': 'zw',
            'Africa/Maputo': 'mz',
            'Africa/Khartoum': 'sd',
            'America/Sao_Paulo': 'br',
        }
        // Try to match the timezone exactly
        if (timezoneCountryMap[tz]) {
            console.log(`Timezone: ${tz}, Country: ${timezoneCountryMap[tz]}`)
            return timezoneCountryMap[tz]
        }
        // Try to match by region if possible
        return null
    } catch (error) {
        console.error('Error inferring user country from timezone:', error)
        return null
    }
}
